package com.jbb.user.biz.mapper;

import com.jbb.user.biz.entity.Intention;
import com.jbb.user.biz.entity.IntentionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IntentionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention
     *
     * @mbggenerated
     */
    int countByExample(IntentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention
     *
     * @mbggenerated
     */
    int deleteByExample(IntentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention
     *
     * @mbggenerated
     */
    int insert(Intention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention
     *
     * @mbggenerated
     */
    int insertSelective(Intention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention
     *
     * @mbggenerated
     */
    List<Intention> selectByExample(IntentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention
     *
     * @mbggenerated
     */
    Intention selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Intention record, @Param("example") IntentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Intention record, @Param("example") IntentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Intention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Intention record);
}