package com.jbb.user.biz.mapper;

import com.jbb.user.biz.entity.IntentionStatus;
import com.jbb.user.biz.entity.IntentionStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IntentionStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    int countByExample(IntentionStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    int deleteByExample(IntentionStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    int insert(IntentionStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    int insertSelective(IntentionStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    List<IntentionStatus> selectByExample(IntentionStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    IntentionStatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") IntentionStatus record, @Param("example") IntentionStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") IntentionStatus record, @Param("example") IntentionStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IntentionStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IntentionStatus record);
}