package com.jbb.user.biz.mapper;

import com.jbb.user.biz.entity.JbbResource;
import com.jbb.user.biz.entity.JbbResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JbbResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_resource
     *
     * @mbggenerated
     */
    int countByExample(JbbResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_resource
     *
     * @mbggenerated
     */
    int deleteByExample(JbbResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_resource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_resource
     *
     * @mbggenerated
     */
    int insert(JbbResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_resource
     *
     * @mbggenerated
     */
    int insertSelective(JbbResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_resource
     *
     * @mbggenerated
     */
    List<JbbResource> selectByExample(JbbResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_resource
     *
     * @mbggenerated
     */
    JbbResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_resource
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") JbbResource record, @Param("example") JbbResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_resource
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") JbbResource record, @Param("example") JbbResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JbbResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JbbResource record);
}