package com.jbb.user.biz.mapper;

import com.jbb.user.biz.entity.OrderDetailJbb;
import com.jbb.user.biz.entity.OrderDetailJbbExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderDetailJbbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_order_detail
     *
     * @mbggenerated
     */
    int countByExample(OrderDetailJbbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_order_detail
     *
     * @mbggenerated
     */
    int deleteByExample(OrderDetailJbbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_order_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_order_detail
     *
     * @mbggenerated
     */
    int insert(OrderDetailJbb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_order_detail
     *
     * @mbggenerated
     */
    int insertSelective(OrderDetailJbb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_order_detail
     *
     * @mbggenerated
     */
    List<OrderDetailJbb> selectByExample(OrderDetailJbbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_order_detail
     *
     * @mbggenerated
     */
    OrderDetailJbb selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_order_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrderDetailJbb record, @Param("example") OrderDetailJbbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_order_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrderDetailJbb record, @Param("example") OrderDetailJbbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_order_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderDetailJbb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_order_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderDetailJbb record);
}