package com.jbb.user.biz.mapper;

import com.jbb.user.biz.entity.OrderLog;
import com.jbb.user.biz.entity.OrderLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_order_log
     *
     * @mbggenerated
     */
    int countByExample(OrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_order_log
     *
     * @mbggenerated
     */
    int deleteByExample(OrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_order_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_order_log
     *
     * @mbggenerated
     */
    int insert(OrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_order_log
     *
     * @mbggenerated
     */
    int insertSelective(OrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_order_log
     *
     * @mbggenerated
     */
    List<OrderLog> selectByExample(OrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_order_log
     *
     * @mbggenerated
     */
    OrderLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_order_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrderLog record, @Param("example") OrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_order_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrderLog record, @Param("example") OrderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_order_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_order_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderLog record);
}