package com.jbb.user.biz.mapper;

import com.jbb.user.biz.entity.PaymentInfo;
import com.jbb.user.biz.entity.PaymentInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_payment_info
     *
     * @mbggenerated
     */
    int countByExample(PaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_payment_info
     *
     * @mbggenerated
     */
    int deleteByExample(PaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_payment_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_payment_info
     *
     * @mbggenerated
     */
    int insert(PaymentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_payment_info
     *
     * @mbggenerated
     */
    int insertSelective(PaymentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_payment_info
     *
     * @mbggenerated
     */
    List<PaymentInfo> selectByExample(PaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_payment_info
     *
     * @mbggenerated
     */
    PaymentInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_payment_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PaymentInfo record, @Param("example") PaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_payment_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PaymentInfo record, @Param("example") PaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_payment_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PaymentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_payment_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PaymentInfo record);
}