package com.jbb.user.biz.mapper;

import com.jbb.user.biz.entity.StatusWorkFlow;
import com.jbb.user.biz.entity.StatusWorkFlowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StatusWorkFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_work_flow
     *
     * @mbggenerated
     */
    int countByExample(StatusWorkFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_work_flow
     *
     * @mbggenerated
     */
    int deleteByExample(StatusWorkFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_work_flow
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_work_flow
     *
     * @mbggenerated
     */
    int insert(StatusWorkFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_work_flow
     *
     * @mbggenerated
     */
    int insertSelective(StatusWorkFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_work_flow
     *
     * @mbggenerated
     */
    List<StatusWorkFlow> selectByExample(StatusWorkFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_work_flow
     *
     * @mbggenerated
     */
    StatusWorkFlow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_work_flow
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StatusWorkFlow record, @Param("example") StatusWorkFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_work_flow
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StatusWorkFlow record, @Param("example") StatusWorkFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_work_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StatusWorkFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_work_flow
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StatusWorkFlow record);
}