package com.jbb.user.biz.entity;

public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_area.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_area.code
     *
     * @mbggenerated
     */
    private Integer code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_area.parentId
     *
     * @mbggenerated
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_area.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_area.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_area.is_administrative_address
     *
     * @mbggenerated
     */
    private Boolean isAdministrativeAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_area.id
     *
     * @return the value of jbb_area.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_area.id
     *
     * @param id the value for jbb_area.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_area.code
     *
     * @return the value of jbb_area.code
     *
     * @mbggenerated
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_area.code
     *
     * @param code the value for jbb_area.code
     *
     * @mbggenerated
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_area.parentId
     *
     * @return the value of jbb_area.parentId
     *
     * @mbggenerated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_area.parentId
     *
     * @param parentid the value for jbb_area.parentId
     *
     * @mbggenerated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_area.name
     *
     * @return the value of jbb_area.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_area.name
     *
     * @param name the value for jbb_area.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_area.level
     *
     * @return the value of jbb_area.level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_area.level
     *
     * @param level the value for jbb_area.level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_area.is_administrative_address
     *
     * @return the value of jbb_area.is_administrative_address
     *
     * @mbggenerated
     */
    public Boolean getIsAdministrativeAddress() {
        return isAdministrativeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_area.is_administrative_address
     *
     * @param isAdministrativeAddress the value for jbb_area.is_administrative_address
     *
     * @mbggenerated
     */
    public void setIsAdministrativeAddress(Boolean isAdministrativeAddress) {
        this.isAdministrativeAddress = isAdministrativeAddress;
    }
}