package com.jbb.user.biz.entity;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_category.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_category.group_name
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_category.service_code
     *
     * @mbggenerated
     */
    private String serviceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_category.service_name
     *
     * @mbggenerated
     */
    private String serviceName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_category.id
     *
     * @return the value of jbb_category.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_category.id
     *
     * @param id the value for jbb_category.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_category.group_name
     *
     * @return the value of jbb_category.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_category.group_name
     *
     * @param groupName the value for jbb_category.group_name
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_category.service_code
     *
     * @return the value of jbb_category.service_code
     *
     * @mbggenerated
     */
    public String getServiceCode() {
        return serviceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_category.service_code
     *
     * @param serviceCode the value for jbb_category.service_code
     *
     * @mbggenerated
     */
    public void setServiceCode(String serviceCode) {
        this.serviceCode = serviceCode == null ? null : serviceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_category.service_name
     *
     * @return the value of jbb_category.service_name
     *
     * @mbggenerated
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_category.service_name
     *
     * @param serviceName the value for jbb_category.service_name
     *
     * @mbggenerated
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName == null ? null : serviceName.trim();
    }
}