package com.jbb.user.biz.entity;

import java.util.ArrayList;
import java.util.List;

public class IntentionStatusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    protected Integer limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    public IntentionStatusExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusIdIsNull() {
            addCriterion("intention_status_id is null");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusIdIsNotNull() {
            addCriterion("intention_status_id is not null");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusIdEqualTo(String value) {
            addCriterion("intention_status_id =", value, "intentionStatusId");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusIdNotEqualTo(String value) {
            addCriterion("intention_status_id <>", value, "intentionStatusId");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusIdGreaterThan(String value) {
            addCriterion("intention_status_id >", value, "intentionStatusId");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusIdGreaterThanOrEqualTo(String value) {
            addCriterion("intention_status_id >=", value, "intentionStatusId");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusIdLessThan(String value) {
            addCriterion("intention_status_id <", value, "intentionStatusId");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusIdLessThanOrEqualTo(String value) {
            addCriterion("intention_status_id <=", value, "intentionStatusId");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusIdLike(String value) {
            addCriterion("intention_status_id like", value, "intentionStatusId");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusIdNotLike(String value) {
            addCriterion("intention_status_id not like", value, "intentionStatusId");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusIdIn(List<String> values) {
            addCriterion("intention_status_id in", values, "intentionStatusId");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusIdNotIn(List<String> values) {
            addCriterion("intention_status_id not in", values, "intentionStatusId");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusIdBetween(String value1, String value2) {
            addCriterion("intention_status_id between", value1, value2, "intentionStatusId");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusIdNotBetween(String value1, String value2) {
            addCriterion("intention_status_id not between", value1, value2, "intentionStatusId");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNameIsNull() {
            addCriterion("intention_status_name is null");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNameIsNotNull() {
            addCriterion("intention_status_name is not null");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNameEqualTo(String value) {
            addCriterion("intention_status_name =", value, "intentionStatusName");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNameNotEqualTo(String value) {
            addCriterion("intention_status_name <>", value, "intentionStatusName");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNameGreaterThan(String value) {
            addCriterion("intention_status_name >", value, "intentionStatusName");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNameGreaterThanOrEqualTo(String value) {
            addCriterion("intention_status_name >=", value, "intentionStatusName");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNameLessThan(String value) {
            addCriterion("intention_status_name <", value, "intentionStatusName");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNameLessThanOrEqualTo(String value) {
            addCriterion("intention_status_name <=", value, "intentionStatusName");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNameLike(String value) {
            addCriterion("intention_status_name like", value, "intentionStatusName");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNameNotLike(String value) {
            addCriterion("intention_status_name not like", value, "intentionStatusName");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNameIn(List<String> values) {
            addCriterion("intention_status_name in", values, "intentionStatusName");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNameNotIn(List<String> values) {
            addCriterion("intention_status_name not in", values, "intentionStatusName");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNameBetween(String value1, String value2) {
            addCriterion("intention_status_name between", value1, value2, "intentionStatusName");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNameNotBetween(String value1, String value2) {
            addCriterion("intention_status_name not between", value1, value2, "intentionStatusName");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNotesIsNull() {
            addCriterion("intention_status_notes is null");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNotesIsNotNull() {
            addCriterion("intention_status_notes is not null");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNotesEqualTo(String value) {
            addCriterion("intention_status_notes =", value, "intentionStatusNotes");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNotesNotEqualTo(String value) {
            addCriterion("intention_status_notes <>", value, "intentionStatusNotes");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNotesGreaterThan(String value) {
            addCriterion("intention_status_notes >", value, "intentionStatusNotes");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNotesGreaterThanOrEqualTo(String value) {
            addCriterion("intention_status_notes >=", value, "intentionStatusNotes");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNotesLessThan(String value) {
            addCriterion("intention_status_notes <", value, "intentionStatusNotes");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNotesLessThanOrEqualTo(String value) {
            addCriterion("intention_status_notes <=", value, "intentionStatusNotes");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNotesLike(String value) {
            addCriterion("intention_status_notes like", value, "intentionStatusNotes");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNotesNotLike(String value) {
            addCriterion("intention_status_notes not like", value, "intentionStatusNotes");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNotesIn(List<String> values) {
            addCriterion("intention_status_notes in", values, "intentionStatusNotes");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNotesNotIn(List<String> values) {
            addCriterion("intention_status_notes not in", values, "intentionStatusNotes");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNotesBetween(String value1, String value2) {
            addCriterion("intention_status_notes between", value1, value2, "intentionStatusNotes");
            return (Criteria) this;
        }

        public Criteria andIntentionStatusNotesNotBetween(String value1, String value2) {
            addCriterion("intention_status_notes not between", value1, value2, "intentionStatusNotes");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jbb_intention_status
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jbb_intention_status
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}