package com.jbb.user.biz.entity;

import java.util.Date;

public class OrderStatusFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_order_status_flow.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_order_status_flow.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_order_status_flow.status_id
     *
     * @mbggenerated
     */
    private String statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_order_status_flow.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_order_status_flow.id
     *
     * @return the value of jbb_order_status_flow.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_order_status_flow.id
     *
     * @param id the value for jbb_order_status_flow.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_order_status_flow.order_id
     *
     * @return the value of jbb_order_status_flow.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_order_status_flow.order_id
     *
     * @param orderId the value for jbb_order_status_flow.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_order_status_flow.status_id
     *
     * @return the value of jbb_order_status_flow.status_id
     *
     * @mbggenerated
     */
    public String getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_order_status_flow.status_id
     *
     * @param statusId the value for jbb_order_status_flow.status_id
     *
     * @mbggenerated
     */
    public void setStatusId(String statusId) {
        this.statusId = statusId == null ? null : statusId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_order_status_flow.create_time
     *
     * @return the value of jbb_order_status_flow.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_order_status_flow.create_time
     *
     * @param createTime the value for jbb_order_status_flow.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}