package com.jbb.user.biz.entity;

public class OrderStatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_order_status.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_order_status.order_status_id
     *
     * @mbggenerated
     */
    private String orderStatusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_order_status.order_status_name
     *
     * @mbggenerated
     */
    private String orderStatusName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_order_status.change_to_next
     *
     * @mbggenerated
     */
    private Integer changeToNext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_order_status.order_status_notes
     *
     * @mbggenerated
     */
    private String orderStatusNotes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_order_status.status_type_name
     *
     * @mbggenerated
     */
    private String statusTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_order_status.status_type
     *
     * @mbggenerated
     */
    private String statusType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_order_status.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_order_status.id
     *
     * @return the value of jbb_order_status.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_order_status.id
     *
     * @param id the value for jbb_order_status.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_order_status.order_status_id
     *
     * @return the value of jbb_order_status.order_status_id
     *
     * @mbggenerated
     */
    public String getOrderStatusId() {
        return orderStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_order_status.order_status_id
     *
     * @param orderStatusId the value for jbb_order_status.order_status_id
     *
     * @mbggenerated
     */
    public void setOrderStatusId(String orderStatusId) {
        this.orderStatusId = orderStatusId == null ? null : orderStatusId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_order_status.order_status_name
     *
     * @return the value of jbb_order_status.order_status_name
     *
     * @mbggenerated
     */
    public String getOrderStatusName() {
        return orderStatusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_order_status.order_status_name
     *
     * @param orderStatusName the value for jbb_order_status.order_status_name
     *
     * @mbggenerated
     */
    public void setOrderStatusName(String orderStatusName) {
        this.orderStatusName = orderStatusName == null ? null : orderStatusName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_order_status.change_to_next
     *
     * @return the value of jbb_order_status.change_to_next
     *
     * @mbggenerated
     */
    public Integer getChangeToNext() {
        return changeToNext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_order_status.change_to_next
     *
     * @param changeToNext the value for jbb_order_status.change_to_next
     *
     * @mbggenerated
     */
    public void setChangeToNext(Integer changeToNext) {
        this.changeToNext = changeToNext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_order_status.order_status_notes
     *
     * @return the value of jbb_order_status.order_status_notes
     *
     * @mbggenerated
     */
    public String getOrderStatusNotes() {
        return orderStatusNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_order_status.order_status_notes
     *
     * @param orderStatusNotes the value for jbb_order_status.order_status_notes
     *
     * @mbggenerated
     */
    public void setOrderStatusNotes(String orderStatusNotes) {
        this.orderStatusNotes = orderStatusNotes == null ? null : orderStatusNotes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_order_status.status_type_name
     *
     * @return the value of jbb_order_status.status_type_name
     *
     * @mbggenerated
     */
    public String getStatusTypeName() {
        return statusTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_order_status.status_type_name
     *
     * @param statusTypeName the value for jbb_order_status.status_type_name
     *
     * @mbggenerated
     */
    public void setStatusTypeName(String statusTypeName) {
        this.statusTypeName = statusTypeName == null ? null : statusTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_order_status.status_type
     *
     * @return the value of jbb_order_status.status_type
     *
     * @mbggenerated
     */
    public String getStatusType() {
        return statusType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_order_status.status_type
     *
     * @param statusType the value for jbb_order_status.status_type
     *
     * @mbggenerated
     */
    public void setStatusType(String statusType) {
        this.statusType = statusType == null ? null : statusType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_order_status.remark
     *
     * @return the value of jbb_order_status.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_order_status.remark
     *
     * @param remark the value for jbb_order_status.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}