package com.jbb.user.biz.entity;

public class StatusWorkFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_work_flow.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_work_flow.status_id
     *
     * @mbggenerated
     */
    private String statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_work_flow.status_name
     *
     * @mbggenerated
     */
    private String statusName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_work_flow.status_next_id
     *
     * @mbggenerated
     */
    private String statusNextId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_work_flow.status_next_name
     *
     * @mbggenerated
     */
    private String statusNextName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_work_flow.status_type_name
     *
     * @mbggenerated
     */
    private String statusTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_work_flow.status_type
     *
     * @mbggenerated
     */
    private String statusType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_work_flow.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_work_flow.id
     *
     * @return the value of jbb_work_flow.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_work_flow.id
     *
     * @param id the value for jbb_work_flow.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_work_flow.status_id
     *
     * @return the value of jbb_work_flow.status_id
     *
     * @mbggenerated
     */
    public String getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_work_flow.status_id
     *
     * @param statusId the value for jbb_work_flow.status_id
     *
     * @mbggenerated
     */
    public void setStatusId(String statusId) {
        this.statusId = statusId == null ? null : statusId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_work_flow.status_name
     *
     * @return the value of jbb_work_flow.status_name
     *
     * @mbggenerated
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_work_flow.status_name
     *
     * @param statusName the value for jbb_work_flow.status_name
     *
     * @mbggenerated
     */
    public void setStatusName(String statusName) {
        this.statusName = statusName == null ? null : statusName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_work_flow.status_next_id
     *
     * @return the value of jbb_work_flow.status_next_id
     *
     * @mbggenerated
     */
    public String getStatusNextId() {
        return statusNextId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_work_flow.status_next_id
     *
     * @param statusNextId the value for jbb_work_flow.status_next_id
     *
     * @mbggenerated
     */
    public void setStatusNextId(String statusNextId) {
        this.statusNextId = statusNextId == null ? null : statusNextId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_work_flow.status_next_name
     *
     * @return the value of jbb_work_flow.status_next_name
     *
     * @mbggenerated
     */
    public String getStatusNextName() {
        return statusNextName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_work_flow.status_next_name
     *
     * @param statusNextName the value for jbb_work_flow.status_next_name
     *
     * @mbggenerated
     */
    public void setStatusNextName(String statusNextName) {
        this.statusNextName = statusNextName == null ? null : statusNextName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_work_flow.status_type_name
     *
     * @return the value of jbb_work_flow.status_type_name
     *
     * @mbggenerated
     */
    public String getStatusTypeName() {
        return statusTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_work_flow.status_type_name
     *
     * @param statusTypeName the value for jbb_work_flow.status_type_name
     *
     * @mbggenerated
     */
    public void setStatusTypeName(String statusTypeName) {
        this.statusTypeName = statusTypeName == null ? null : statusTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_work_flow.status_type
     *
     * @return the value of jbb_work_flow.status_type
     *
     * @mbggenerated
     */
    public String getStatusType() {
        return statusType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_work_flow.status_type
     *
     * @param statusType the value for jbb_work_flow.status_type
     *
     * @mbggenerated
     */
    public void setStatusType(String statusType) {
        this.statusType = statusType == null ? null : statusType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbb_work_flow.remark
     *
     * @return the value of jbb_work_flow.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbb_work_flow.remark
     *
     * @param remark the value for jbb_work_flow.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}