package com.jbb.enterprise.app.request.order;

public class IntentionRequest {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column jbb_intention.user_id
	 *
	 * @mbggenerated
	 */
	private Integer userId;

	private String industryCode;

	public String getIndustryCode() {
		return industryCode;
	}

	public void setIndustryCode(String industryCode) {
		this.industryCode = industryCode;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column jbb_intention.contact_name
	 *
	 * @mbggenerated
	 */
	private String contactName;

	public Integer getProductId() {
		return productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	private Integer productId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column jbb_intention.contact_phone
	 *
	 * @mbggenerated
	 */
	private String contactPhone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column jbb_intention.area_code
	 *
	 * @mbggenerated
	 */
	private String areaCode;

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getContactName() {
		return contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public String getContactPhone() {
		return contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	public String getAreaCode() {
		return areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column jbb_intention.status
	 *
	 * @mbggenerated
	 */
	private String status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column jbb_intention.remark
	 *
	 * @mbggenerated
	 */
	private String remark;

}