package com.jbb.enterprise.app.request.order;

import java.util.List;

public class OrderJbbRequest {

	private String remark;



	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column jbb_order_detail.layer
	 *
	 * @mbggenerated
	 */
	private String number;


	public String getRemark() {
		return remark;
	}

	public String getNumber() {
		return number;
	}

	public void setNumber(String number) {
		this.number = number;
	}


	public void setRemark(String remark) {
		this.remark = remark;
	}

	private List<OrderDetailRequest> orderDetailRequest;

	public List<OrderDetailRequest> getOrderDetailRequest() {
		return orderDetailRequest;
	}

	public void setOrderDetailRequest(List<OrderDetailRequest> orderDetailRequest) {
		this.orderDetailRequest = orderDetailRequest;
	}

}