/**
 * 
 */
package com.jbb.enterprise.app.request.order;

/**
 * @author yangxiangqian
 *
 */
public class OrderDetailRequest {

	private Integer productId;

	public Integer getProductId() {
		return productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public Integer getQuantity() {
		return quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	private Integer quantity;

	private String startTime;
	
    public Integer getYear() {
		return year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public Integer getLayer() {
		return layer;
	}

	public void setLayer(Integer layer) {
		this.layer = layer;
	}

	private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbb_order_detail.layer
     *
     * @mbggenerated
     */
    private Integer layer;

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	private String endTime;

}
