package com.jbb.user.api.dto;

import com.wordnik.swagger.annotations.ApiModelProperty;

public class NumberRequest {

	private String type;

	public Byte getPromptionStatus() {
		return promptionStatus;
	}

	public void setPromptionStatus(Byte promptionStatus) {
		this.promptionStatus = promptionStatus;
	}

	@ApiModelProperty(value = "0为非促销， 1为促销", notes = "0为非促销， 1为促销")
	private Byte promptionStatus;

	@ApiModelProperty(value = "TOP, Super,A,B,C")
	private String level;

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getLevel() {
		return level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public Integer getLimitStart() {
		return limitStart;
	}

	public void setLimitStart(Integer limitStart) {
		this.limitStart = limitStart;
	}

	public Integer getLimitEnd() {
		return limitEnd;
	}

	public void setLimitEnd(Integer limitEnd) {
		this.limitEnd = limitEnd;
	}

	protected Integer limitStart;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table jbb_number
	 *
	 * @mbggenerated
	 */
	protected Integer limitEnd;

}