package com.jbb.user.api.dto;

import java.util.Date;
import java.util.List;

import com.jbb.user.biz.entity.OrderDetailJbb;

public class OrderJbbDTO {

	private List<OrderDetailJbb> detailList;
	public List<OrderDetailJbb> getDetailList() {
		return detailList;
	}

	public void setDetailList(List<OrderDetailJbb> detailList) {
		this.detailList = detailList;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column jbb_order.id
	 *
	 * @mbggenerated
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column jbb_order.orderid
	 *
	 * @mbggenerated
	 */
	private String orderid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column jbb_order.user_id
	 *
	 * @mbggenerated
	 */
	private Integer userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column jbb_order.price
	 *
	 * @mbggenerated
	 */
	private Integer price;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column jbb_order.coupon_amout
	 *
	 * @mbggenerated
	 */
	private Integer couponAmout;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column jbb_order.jbbcoin_amount
	 *
	 * @mbggenerated
	 */
	private Integer jbbcoinAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column jbb_order.pay_amount
	 *
	 * @mbggenerated
	 */
	private Integer payAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column jbb_order.status
	 *
	 * @mbggenerated
	 */
	private String status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column jbb_order.createTime
	 *
	 * @mbggenerated
	 */
	private Date createtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column jbb_order.updateTime
	 *
	 * @mbggenerated
	 */
	private Date updatetime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column jbb_order.remark
	 *
	 * @mbggenerated
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column jbb_order.id
	 *
	 * @return the value of jbb_order.id
	 *
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column jbb_order.id
	 *
	 * @param id
	 *            the value for jbb_order.id
	 *
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column jbb_order.orderid
	 *
	 * @return the value of jbb_order.orderid
	 *
	 * @mbggenerated
	 */
	public String getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column jbb_order.orderid
	 *
	 * @param orderid
	 *            the value for jbb_order.orderid
	 *
	 * @mbggenerated
	 */
	public void setOrderid(String orderid) {
		this.orderid = orderid == null ? null : orderid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column jbb_order.user_id
	 *
	 * @return the value of jbb_order.user_id
	 *
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column jbb_order.user_id
	 *
	 * @param userId
	 *            the value for jbb_order.user_id
	 *
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column jbb_order.price
	 *
	 * @return the value of jbb_order.price
	 *
	 * @mbggenerated
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column jbb_order.price
	 *
	 * @param price
	 *            the value for jbb_order.price
	 *
	 * @mbggenerated
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column jbb_order.coupon_amout
	 *
	 * @return the value of jbb_order.coupon_amout
	 *
	 * @mbggenerated
	 */
	public Integer getCouponAmout() {
		return couponAmout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column jbb_order.coupon_amout
	 *
	 * @param couponAmout
	 *            the value for jbb_order.coupon_amout
	 *
	 * @mbggenerated
	 */
	public void setCouponAmout(Integer couponAmout) {
		this.couponAmout = couponAmout;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column jbb_order.jbbcoin_amount
	 *
	 * @return the value of jbb_order.jbbcoin_amount
	 *
	 * @mbggenerated
	 */
	public Integer getJbbcoinAmount() {
		return jbbcoinAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column jbb_order.jbbcoin_amount
	 *
	 * @param jbbcoinAmount
	 *            the value for jbb_order.jbbcoin_amount
	 *
	 * @mbggenerated
	 */
	public void setJbbcoinAmount(Integer jbbcoinAmount) {
		this.jbbcoinAmount = jbbcoinAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column jbb_order.pay_amount
	 *
	 * @return the value of jbb_order.pay_amount
	 *
	 * @mbggenerated
	 */
	public Integer getPayAmount() {
		return payAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column jbb_order.pay_amount
	 *
	 * @param payAmount
	 *            the value for jbb_order.pay_amount
	 *
	 * @mbggenerated
	 */
	public void setPayAmount(Integer payAmount) {
		this.payAmount = payAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column jbb_order.status
	 *
	 * @return the value of jbb_order.status
	 *
	 * @mbggenerated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column jbb_order.status
	 *
	 * @param status
	 *            the value for jbb_order.status
	 *
	 * @mbggenerated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column jbb_order.createTime
	 *
	 * @return the value of jbb_order.createTime
	 *
	 * @mbggenerated
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column jbb_order.createTime
	 *
	 * @param createtime
	 *            the value for jbb_order.createTime
	 *
	 * @mbggenerated
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column jbb_order.updateTime
	 *
	 * @return the value of jbb_order.updateTime
	 *
	 * @mbggenerated
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column jbb_order.updateTime
	 *
	 * @param updatetime
	 *            the value for jbb_order.updateTime
	 *
	 * @mbggenerated
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column jbb_order.remark
	 *
	 * @return the value of jbb_order.remark
	 *
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column jbb_order.remark
	 *
	 * @param remark
	 *            the value for jbb_order.remark
	 *
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

}